### ISSUE TITLE
Download file from cloudflare protected site.

### ISSUE THREAD

**Issue by JinZhuXing** [sandpipes/cpp-cloudflare-scraper#1]
Hello.
Thank you for your project.

I am going to download signature file (.cvd) from clamav site which was protected with Cloudflare.
https://database.clamav.net/daily.cvd

So, I just tried with this code, but first time it success get cookie, but next time, it fails.
And after getting cookie, how can I download with this cookie?

Please teach me.
Thank you.

**Comment by sandpipes** [comment]
I don't believe this code works anymore as cloudflare likes to update their protection often.

You can probably get it to work again if you update the methods to use their latest code to run it, check here https://github.com/Anorov/cloudflare-scrape for how they do it.

I'm likely not going to update this project as well.
